[package]
name = "ggo_emu_panel"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/ggo_emu_panel.rs"

[dependencies]
async-channel.workspace = true
gpui.workspace = true
image.workspace = true
keymap_editor.workspace = true
project.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true
ggo-emu-core.workspace = true # GGO

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
project = { workspace = true, features = ["test-support"] }
tempfile.workspace = true
workspace = { workspace = true, features = ["test-support"] }
