[package]
name = "ggo_metasprite_panel"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/ggo_metasprite_panel.rs"

[dependencies]
editor.workspace = true
ggo-worldlib.workspace = true # GGO
ggo_common.workspace = true
gpui.workspace = true
keymap_editor.workspace = true
ui.workspace = true
workspace.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
project = { workspace = true, features = ["test-support"] }
tempfile.workspace = true
workspace = { workspace = true, features = ["test-support"] }
