[package]
name = "zedgg_project_db"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/zedgg_project_db.rs"

[dependencies]
anyhow.workspace = true
sqlez.workspace = true

[dev-dependencies]
tempfile.workspace = true
